-- Batch 3: Education (12) + Veterans (10) + Arts (10) = 32 grants

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Federal Pell Grant', 'U.S. Department of Education', 'individual', 'education', 'The Pell Grant is the largest federal grant program for undergraduate students, providing need-based aid that does not need to be repaid. Awards are determined by financial need, cost of attendance, enrollment status, and whether the student attends full- or part-time. Students may receive up to 12 semesters (6 years) of Pell Grant funding over their academic careers.', 7395, TRUE, NULL, '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_financial_need": true}'::jsonb, '["FAFSA application", "Social Security Number or Alien Registration Number", "Federal tax returns", "Bank statements", "Enrollment verification"]'::jsonb, 'https://studentaid.gov/h/apply-for-aid/fafsa', 'https://studentaid.gov/understand-aid/types/grants/pell', '["FAFSA"]'::jsonb, 30, 'federal-pell-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Federal Supplemental Educational Opportunity Grant (FSEOG)', 'U.S. Department of Education', 'individual', 'education', 'FSEOG is a campus-based aid program providing grants to undergraduates with exceptional financial need, with priority given to Pell Grant recipients. Unlike the Pell Grant, FSEOG funds are administered directly by the financial aid office at participating schools. The amount a student can receive depends on when they apply, their financial need, and the funding level of their school.', 4000, TRUE, NULL, '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_exceptional_financial_need": true}'::jsonb, '["FAFSA application", "Enrollment verification", "Financial need documentation"]'::jsonb, 'https://studentaid.gov/understand-aid/types/grants/fseog', 'https://studentaid.gov/understand-aid/types/grants/fseog', '[]'::jsonb, 30, 'federal-supplemental-educational-opportunity-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('TEACH Grant', 'U.S. Department of Education', 'individual', 'education', 'The Teacher Education Assistance for College and Higher Education (TEACH) Grant provides up to $4,000 per year to students who plan to become teachers in high-need fields (such as math, science, and special education) at low-income schools. Recipients must teach for at least 4 years within 8 years of completing the program; otherwise the grant converts to an unsubsidized Direct Loan.', 4000, TRUE, NULL, '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_teaching_commitment": true}'::jsonb, '["FAFSA application", "TEACH Grant Agreement to Serve", "Enrollment in TEACH-eligible program", "Academic achievement documentation (GPA 3.25+ or top 75% on college admissions test)"]'::jsonb, 'https://studentaid.gov/understand-aid/types/grants/teach', 'https://studentaid.gov/understand-aid/types/grants/teach', '[]'::jsonb, 30, 'teach-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Iraq and Afghanistan Service Grant', 'U.S. Department of Education', 'individual', 'education', 'The Iraq and Afghanistan Service Grant is available to students whose parent or guardian died as a result of military service in Iraq or Afghanistan after September 11, 2001. The student must not be eligible for a Pell Grant based on financial need but must meet all other Pell eligibility requirements. The grant amount equals the maximum Pell Grant award for the award year.', 7395, TRUE, NULL, '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_military_parent_loss": true}'::jsonb, '["FAFSA application", "Documentation of parent/guardian military death", "Enrollment verification"]'::jsonb, 'https://studentaid.gov/understand-aid/types/grants/iraq-afghanistan-service', 'https://studentaid.gov/understand-aid/types/grants/iraq-afghanistan-service', '[]'::jsonb, 45, 'iraq-afghanistan-service-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Gates Scholarship', 'Gates Scholarship Program', 'individual', 'education', 'The Gates Scholarship is a highly competitive, full scholarship for exceptional, Pell-eligible, minority high school seniors in the United States. It aims to promote the personal and professional growth of outstanding minority students. The scholarship covers the full cost of attendance minus other aid and allows recipients to pursue any field of study at any accredited U.S. college or university.', 50000, TRUE, '2025-09-15', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_minority": true, "requires_financial_need": true, "requires_high_school_senior": true}'::jsonb, '["Online application", "High school transcript", "SAT/ACT scores", "Recommendation letters (3)", "Personal essays", "Financial aid information"]'::jsonb, 'https://www.thegatesscholarship.org/scholarship', 'https://www.thegatesscholarship.org', '[]'::jsonb, 90, 'gates-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Thurgood Marshall College Fund Scholarship', 'Thurgood Marshall College Fund', 'individual', 'education', 'The Thurgood Marshall College Fund provides merit and need-based scholarships to students attending its 47 member Historically Black Colleges and Universities (HBCUs) and Predominantly Black Institutions (PBIs). Scholarships support students in all fields of study and connect recipients with corporate and government partners for internship and career opportunities.', 10000, TRUE, '2026-02-28', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_hbcu_enrollment": true, "min_gpa": 3.0}'::jsonb, '["Online application", "College transcript", "Financial need documentation", "Recommendation letters (2)", "Personal statement", "FAFSA EFC"]'::jsonb, 'https://tmcf.org/students-alumni/scholarship/tmcf-scholarships/', 'https://tmcf.org', '[]'::jsonb, 90, 'thurgood-marshall-college-fund-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Hispanic Scholarship Fund Grant', 'Hispanic Scholarship Fund', 'individual', 'education', 'The Hispanic Scholarship Fund (HSF) provides scholarships to Hispanic students pursuing a college degree in the U.S. HSF is the nation''s largest nonprofit organization supporting Hispanic higher education, having awarded more than $600 million in scholarships since 1975. Awards range from $500 to $5,000 based on merit and financial need.', 5000, TRUE, '2026-02-15', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_hispanic_heritage": true, "min_gpa": 3.0}'::jsonb, '["Online application", "College transcript", "Financial need documentation", "Personal essay", "FAFSA SAR"]'::jsonb, 'https://www.hsf.net/scholarship', 'https://www.hsf.net', '[]'::jsonb, 90, 'hispanic-scholarship-fund-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('American Indian College Fund Scholarship', 'American Indian College Fund', 'individual', 'education', 'The American Indian College Fund is the nation''s largest American Indian higher education charity, providing scholarships to Native American students. The fund supports students at tribal colleges and mainstream universities and offers over $8 million in scholarships annually. Awards support students in any field of study, with some scholarships targeting specific majors or career paths.', 5000, TRUE, '2026-05-31', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_native_american_heritage": true}'::jsonb, '["Online application", "Tribal enrollment documentation", "College transcript", "Financial need documentation", "Personal essay"]'::jsonb, 'https://collegefund.org/students/scholarships/', 'https://collegefund.org', '[]'::jsonb, 90, 'american-indian-college-fund-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Jack Kent Cooke Foundation College Scholarship', 'Jack Kent Cooke Foundation', 'individual', 'education', 'The Jack Kent Cooke College Scholarship Program is one of the largest private scholarships in the country for high-achieving students with financial need. It provides up to $40,000 per year for up to four years of undergraduate study. The program selects scholars who have demonstrated academic ability and ambition, and it provides ongoing advising and support throughout college.', 40000, TRUE, '2025-11-20', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_high_school_senior": true, "requires_financial_need": true, "min_gpa": 3.5}'::jsonb, '["Online application", "High school transcript", "Standardized test scores", "Recommendation letters (3)", "Personal essay", "Financial need documentation"]'::jsonb, 'https://www.jkcf.org/our-scholarships/college-scholarship-program/', 'https://www.jkcf.org', '[]'::jsonb, 120, 'jack-kent-cooke-foundation-college-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Dell Scholars Program', 'Michael & Susan Dell Foundation', 'individual', 'education', 'The Dell Scholars Program recognizes and supports students who have overcome significant obstacles to pursue their education. The program awards $20,000 scholarships plus a laptop, online resources, and ongoing support services. Scholars receive a dedicated support system that includes financial advising, emergency fund access, and a community of fellow Dell Scholars.', 20000, TRUE, '2025-12-01', '{"requires_us_citizen": true, "requires_student": true, "education_level": "undergraduate", "requires_high_school_senior": true, "requires_financial_need": true, "min_gpa": 2.4}'::jsonb, '["Online application", "FAFSA", "High school transcript", "Personal essays", "Letters of recommendation (2)"]'::jsonb, 'https://www.dellscholars.org/scholarship/', 'https://www.dellscholars.org', '[]'::jsonb, 90, 'dell-scholars-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Coca-Cola Scholars Program', 'Coca-Cola Scholars Foundation', 'individual', 'education', 'The Coca-Cola Scholars Program is a merit-based scholarship awarded to 150 graduating high school seniors each year. Recipients receive $20,000 for undergraduate study at any accredited U.S. college or university. Scholars are selected based on leadership, service, and academic achievement, and gain access to a lifelong network of over 6,600 alumni leaders.', 20000, TRUE, '2025-10-31', '{"requires_us_citizen": true, "requires_student": true, "requires_high_school_senior": true, "education_level": "undergraduate", "min_gpa": 3.0}'::jsonb, '["Online application", "High school transcript", "Personal essays", "Letters of recommendation (2)", "Extracurricular activities list"]'::jsonb, 'https://www.coca-colascholarsfoundation.org/apply/', 'https://www.coca-colascholarsfoundation.org', '[]'::jsonb, 90, 'coca-cola-scholars-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('QuestBridge National College Match Scholarship', 'QuestBridge', 'individual', 'education', 'QuestBridge connects high-achieving, low-income students with full four-year scholarships to some of the nation''s leading colleges and universities. The National College Match allows finalists to rank up to 12 partner colleges and receive a binding admissions decision with a full scholarship covering tuition, room, board, and fees. Over 45 leading colleges partner with QuestBridge.', 250000, TRUE, '2025-09-26', '{"requires_us_citizen": true, "requires_student": true, "requires_high_school_senior": true, "education_level": "undergraduate", "requires_financial_need": true, "max_household_income": 65000}'::jsonb, '["Online application", "High school transcript", "Standardized test scores", "Essays (6 short essays)", "Financial information", "Counselor recommendation"]'::jsonb, 'https://www.questbridge.org/apply', 'https://www.questbridge.org', '[]'::jsonb, 60, 'questbridge-national-college-match-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Post-9/11 GI Bill (Chapter 33)', 'U.S. Department of Veterans Affairs', 'individual', 'veterans', 'The Post-9/11 GI Bill provides financial support for education and housing for individuals who have served on active duty for 90 or more days after September 10, 2001. Benefits include tuition and fees, a monthly housing allowance, and a stipend for books and supplies. Benefit levels range from 40% to 100% based on length of active duty service.', 28937, TRUE, NULL, '{"requires_us_veteran": true, "requires_active_duty_service": true, "min_service_days": 90, "service_after": "2001-09-10"}'::jsonb, '["VA Form 22-1990", "DD-214 Certificate of Release", "Enrollment certification", "Social Security Number", "Direct deposit information"]'::jsonb, 'https://www.va.gov/education/how-to-apply/', 'https://www.va.gov/education/about-gi-bill-benefits/post-9-11/', '["VA Form 22-1990"]'::jsonb, 30, 'post-911-gi-bill')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Montgomery GI Bill – Active Duty (MGIB-AD)', 'U.S. Department of Veterans Affairs', 'individual', 'veterans', 'The Montgomery GI Bill Active Duty (MGIB-AD) provides up to 36 months of education benefits for veterans and service members who have at least 2 years of active duty service. Benefits can be used for college, business, technical, or vocational courses; apprenticeships; on-the-job training; and other education and training programs.', 2324, TRUE, NULL, '{"requires_us_veteran": true, "requires_active_duty_service": true, "min_service_months": 24, "requires_honorable_discharge": true}'::jsonb, '["VA Form 22-1990", "DD-214 Certificate of Release", "Enrollment certification"]'::jsonb, 'https://www.va.gov/education/how-to-apply/', 'https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/', '["VA Form 22-1990"]'::jsonb, 30, 'montgomery-gi-bill-active-duty')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('VA Vocational Rehabilitation and Employment (VR&E)', 'U.S. Department of Veterans Affairs', 'individual', 'veterans', 'The VA Vocational Rehabilitation and Employment program (also known as Chapter 31) helps veterans with service-connected disabilities prepare for, find, and maintain suitable employment. The program can also help veterans gain independence in daily living. Benefits include education and training, career counseling, job search assistance, and support for starting a business.', 15000, TRUE, NULL, '{"requires_us_veteran": true, "requires_service_connected_disability": true, "min_disability_rating": 10}'::jsonb, '["VA Form 28-1900", "DD-214 Certificate of Release", "VA disability rating documentation", "Educational records", "Medical documentation"]'::jsonb, 'https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/', 'https://www.va.gov/careers-employment/vocational-rehabilitation/', '["VA Form 28-1900"]'::jsonb, 45, 'va-vocational-rehabilitation-employment')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Folds of Honor Scholarship', 'Folds of Honor Foundation', 'individual', 'veterans', 'Folds of Honor provides educational scholarships to spouses and children of military members who have been killed or disabled while serving in the U.S. Armed Forces. Since 2007, Folds of Honor has awarded over 43,000 scholarships totaling more than $200 million. Scholarships are available for K–12 private school tuition and post-secondary education.', 5000, TRUE, '2026-03-01', '{"requires_military_family": true, "requires_killed_or_disabled_servicemember": true}'::jsonb, '["Online application", "DD-214 or service documentation", "Disability or death documentation", "Enrollment verification", "Personal essay", "Recommendation letter"]'::jsonb, 'https://foldsofhonor.org/scholarships/', 'https://foldsofhonor.org', '[]'::jsonb, 60, 'folds-of-honor-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Pat Tillman Foundation Scholarship', 'Pat Tillman Foundation', 'individual', 'veterans', 'The Pat Tillman Scholarship supports veteran and military scholars pursuing undergraduate and graduate degrees at U.S. colleges and universities. Scholars are selected based on intellectual curiosity, drive, and a commitment to service beyond oneself. The program provides financial support, a network of scholars and mentors, and ongoing leadership development opportunities.', 15000, TRUE, '2026-02-01', '{"requires_us_veteran": true, "requires_student": true}'::jsonb, '["Online application", "Military service documentation", "College transcript", "Personal essays", "Recommendation letters (3)"]'::jsonb, 'https://pattillmanfoundation.org/apply-to-be-a-scholar/', 'https://pattillmanfoundation.org', '[]'::jsonb, 90, 'pat-tillman-foundation-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('American Legion Legacy Scholarship', 'The American Legion', 'individual', 'veterans', 'The American Legion Legacy Scholarship provides financial assistance to children of post-9/11 active duty military personnel killed on active duty or who died as a result of a service-related injury or disease. Scholarships are for full-time undergraduate study at accredited colleges and universities. Awards are based on financial need and may be renewed for up to four years.', 20000, TRUE, '2026-04-15', '{"requires_military_dependent": true, "requires_parent_killed_in_service": true, "requires_student": true, "education_level": "undergraduate"}'::jsonb, '["Online application", "Parent''s DD-214", "Death certificate or casualty documentation", "High school transcript", "Financial need documentation"]'::jsonb, 'https://www.legion.org/scholarships/legacy', 'https://www.legion.org/scholarships', '[]'::jsonb, 60, 'american-legion-legacy-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Veterans of Foreign Wars Voice of Democracy Scholarship', 'Veterans of Foreign Wars', 'individual', 'veterans', 'The VFW Voice of Democracy audio-essay program provides high school students in grades 9–12 with the opportunity to express their opinions on democracy and patriotism. Top competitors receive more than $2 million in scholarships each year. The first-place national winner receives a $30,000 scholarship, and state winners receive various awards before competing at the national level.', 30000, TRUE, '2025-10-31', '{"requires_us_citizen": true, "requires_student": true, "requires_high_school_enrollment": true}'::jsonb, '["Audio essay (3-5 minutes)", "Essay transcript", "Application form", "Participation through local VFW post"]'::jsonb, 'https://www.vfw.org/community/youth-and-education/youth-scholarships', 'https://www.vfw.org', '[]'::jsonb, 90, 'vfw-voice-of-democracy-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('AMVETS National Scholarship', 'AMVETS', 'individual', 'veterans', 'AMVETS (American Veterans) provides scholarships to veterans, active duty service members, National Guard members, reservists, and their dependents. Scholarships support undergraduate and graduate education at accredited institutions. AMVETS awards over $300,000 in scholarships annually to support the educational needs of those who have served or are serving the nation.', 4000, TRUE, '2026-04-15', '{"requires_us_veteran_or_dependent": true, "requires_student": true}'::jsonb, '["Online application", "Military service documentation", "College transcript", "Personal essay", "Letter of recommendation"]'::jsonb, 'https://amvets.org/scholarships/', 'https://amvets.org', '[]'::jsonb, 60, 'amvets-national-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Disabled American Veterans Auxiliary Scholarship', 'Disabled American Veterans Auxiliary', 'individual', 'veterans', 'The DAV Auxiliary provides scholarships to children of disabled veterans who are pursuing higher education. The program recognizes the sacrifices made by veterans with service-connected disabilities and helps their children achieve their educational goals. Awards are based on financial need, academic achievement, and community involvement.', 1500, TRUE, '2026-03-01', '{"requires_disabled_veteran_parent": true, "requires_student": true, "education_level": "undergraduate"}'::jsonb, '["Application form", "Parent''s VA disability documentation", "College transcript", "Financial aid information", "Personal statement"]'::jsonb, 'https://www.davauxiliary.org/scholarships', 'https://www.davauxiliary.org', '[]'::jsonb, 60, 'disabled-american-veterans-auxiliary-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Military Officers Association of America Scholarship', 'Military Officers Association of America', 'individual', 'veterans', 'MOAA provides need-based interest-free loans and scholarships for children of military officers for undergraduate study. The program helps junior officers and their families afford higher education. MOAA also administers scholarship programs from various foundations and endowments to support military families pursuing higher education goals.', 5000, TRUE, '2026-03-01', '{"requires_military_officer_dependent": true, "requires_student": true, "education_level": "undergraduate", "requires_financial_need": true}'::jsonb, '["Online application", "Parent''s military service documentation", "College transcript", "Financial need documentation", "Personal essay"]'::jsonb, 'https://www.moaa.org/content/benefits-and-discounts/financial-assistance/scholarship-programs/', 'https://www.moaa.org', '[]'::jsonb, 60, 'moaa-scholarship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NEA Grants for Arts Projects', 'National Endowment for the Arts', 'individual', 'arts', 'NEA Grants for Arts Projects support public engagement with and access to arts, lifelong learning in the arts, and the health of arts sectors. Organizations may apply for projects that feature the creation of art that meets the highest standards of excellence, invite all Americans to participate in and experience the arts, and strengthen the practice of arts learning.', 100000, TRUE, '2026-02-13', '{"requires_us_organization": true, "requires_arts_organization": true, "requires_nonprofit": true}'::jsonb, '["Online application (Grants.gov)", "Project narrative", "Budget", "Organizational profile", "Work samples", "IRS determination letter", "Audited financial statements"]'::jsonb, 'https://www.arts.gov/grants/grants-for-arts-projects', 'https://www.arts.gov', '[]'::jsonb, 120, 'nea-grants-for-arts-projects')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NEA Creative Writing Fellowships', 'National Endowment for the Arts', 'individual', 'arts', 'NEA Creative Writing Fellowships enable recipients to set aside time for writing, research, travel, and other activities that support the creation of new work. The program alternates annually between prose (fiction and creative nonfiction) and poetry. Fellows receive $25,000 and may pursue their projects for 12 months without restriction on how funds are used.', 25000, TRUE, '2026-03-06', '{"requires_us_citizen": true, "requires_published_writer": true}'::jsonb, '["Online application", "Writing samples (up to 25 pages)", "Publication history", "Artist statement"]'::jsonb, 'https://www.arts.gov/grants/creative-writing-fellowships', 'https://www.arts.gov/grants/creative-writing-fellowships', '[]'::jsonb, 180, 'nea-creative-writing-fellowships')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NEA Translation Projects Fellowships', 'National Endowment for the Arts', 'individual', 'arts', 'NEA Translation Projects Fellowships support the translation of literary works into English. Fellowships of $12,500 or $25,000 support translators as they complete book-length literary translation projects including fiction, creative nonfiction, and poetry. These fellowships help introduce international literature to American readers.', 25000, TRUE, '2026-01-16', '{"requires_us_citizen": true, "requires_translator": true}'::jsonb, '["Online application", "Translation samples", "Original text samples", "Project description", "Translator biography"]'::jsonb, 'https://www.arts.gov/grants/translation-projects', 'https://www.arts.gov/grants/translation-projects', '[]'::jsonb, 180, 'nea-translation-projects-fellowships')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Guggenheim Fellowship', 'John Simon Guggenheim Memorial Foundation', 'individual', 'arts', 'Guggenheim Fellowships are intended for men and women who have already demonstrated exceptional capacity for productive scholarship or exceptional creative ability in the arts. The program awards fellowships to artists, writers, scholars, and scientists across all fields. Fellows may use their grants in whatever way they believe will best enable them to pursue their work.', 50000, TRUE, '2025-09-17', '{"requires_us_citizen": true, "requires_demonstrated_achievement": true}'::jsonb, '["Online application", "Career narrative", "Project statement", "Work samples", "Reference letters (3)"]'::jsonb, 'https://www.gf.org/applicants/', 'https://www.gf.org', '[]'::jsonb, 180, 'guggenheim-fellowship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Artist Trust GAP Grants', 'Artist Trust', 'individual', 'arts', 'Artist Trust''s Grants for Artist Projects (GAP) provides support to Washington State artists to help them complete projects or realize artistic goals in any discipline. GAP is a highly competitive, merit-based program that awards between $1,500 and $3,000 to individual artists. Funds can be used for supplies, equipment, travel, living expenses, and other project-related costs.', 3000, TRUE, '2026-01-15', '{"requires_us_resident": true, "requires_washington_state_resident": true, "requires_practicing_artist": true}'::jsonb, '["Online application", "Artist statement", "Work samples (10 images, audio, or video clips)", "Project description and budget"]'::jsonb, 'https://artisttrust.org/awards/gap/', 'https://artisttrust.org', '[]'::jsonb, 90, 'artist-trust-gap-grants')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Creative Capital Award', 'Creative Capital Foundation', 'individual', 'arts', 'Creative Capital supports innovative and adventurous artists across the country through funding, counsel, and career development opportunities. Awardees receive project funding up to $50,000, as well as business and personal development workshops, strategy sessions, public promotion, and a network of over 700 artists across the U.S.', 50000, TRUE, '2026-02-01', '{"requires_us_citizen": true, "requires_practicing_artist": true}'::jsonb, '["Online application", "Artist biography", "Project description", "Work samples", "Budget narrative"]'::jsonb, 'https://creative-capital.org/award/', 'https://creative-capital.org', '[]'::jsonb, 180, 'creative-capital-award')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NEFA National Dance Project Production Grant', 'New England Foundation for the Arts', 'individual', 'arts', 'The National Dance Project (NDP) Production Grant supports the creation of new dance works by U.S.-based choreographers and dance companies. Awards of up to $55,000 help artists create ambitious, fully-realized dance productions. The program also offers touring grants to help bring these works to new audiences across the country.', 55000, TRUE, '2026-01-31', '{"requires_us_citizen": true, "requires_dance_artist": true}'::jsonb, '["Online application", "Project narrative", "Budget", "Artist biography", "Work samples (video)", "Presenter support letters"]'::jsonb, 'https://www.nefa.org/grants-programs/grants/national-dance-project-production-grant', 'https://www.nefa.org', '[]'::jsonb, 90, 'nefa-national-dance-project-production-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('New York Foundation for the Arts Fellowship', 'New York Foundation for the Arts', 'individual', 'arts', 'NYFA Fellowships are cash awards of $7,000 given to individual originating artists living and working in New York State. These unrestricted awards recognize exceptional work and provide artists with financial support and public recognition at crucial stages of their careers. Fellowships rotate through different artistic disciplines each year.', 7000, TRUE, '2026-01-27', '{"requires_us_resident": true, "requires_new_york_state_resident": true, "requires_practicing_artist": true}'::jsonb, '["Online application", "Artist statement", "Work samples", "Resume or CV"]'::jsonb, 'https://www.nyfa.org/fellowships/', 'https://www.nyfa.org', '[]'::jsonb, 120, 'nyfa-fellowship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('WESTAF/NEA Curation Initiative Grant', 'Western States Arts Federation', 'individual', 'arts', 'WESTAF, in partnership with NEA, provides grants to arts organizations in the western United States to support innovative curatorial projects that expand access to the arts. Grants support projects that develop new curatorial approaches, showcase underrepresented artists and art forms, and build connections between communities and artists across the region.', 25000, TRUE, '2026-03-01', '{"requires_us_organization": true, "requires_arts_organization": true, "requires_western_us_location": true}'::jsonb, '["Online application", "Project narrative", "Budget", "Organizational profile", "Work samples"]'::jsonb, 'https://westaf.org/grants/', 'https://westaf.org', '[]'::jsonb, 90, 'westaf-nea-curation-initiative-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('American Music Center Composer Assistance Program', 'New Music USA', 'individual', 'arts', 'New Music USA''s Composer Assistance Program (formerly American Music Center) supports American composers to complete major new works and bring them to performance. The program provides grants for commissioning, recording, and performing new music. Through its grants, New Music USA supports composers at every career stage creating innovative work across all genres.', 15000, TRUE, '2026-02-01', '{"requires_us_citizen": true, "requires_composer": true}'::jsonb, '["Online application", "Work samples (audio recordings or scores)", "Project description", "Budget narrative", "Artist biography"]'::jsonb, 'https://newmusicusa.org/grants/', 'https://newmusicusa.org', '[]'::jsonb, 90, 'new-music-usa-composer-assistance-program')
ON CONFLICT (slug) DO NOTHING;

