-- Batch 4: Housing (10) + Energy (9) + Health (10) = 29 grants

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HUD Section 8 Housing Choice Voucher Program', 'U.S. Department of Housing and Urban Development', 'individual', 'housing', 'The Housing Choice Voucher (HCV) program is the federal government''s major program for assisting very low-income families, the elderly, and the disabled to afford decent, safe, and sanitary housing in the private market. Participants find their own housing and use the voucher to pay for all or part of the rent. The program is administered by local public housing agencies (PHAs).', 24000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "max_household_income_percent_ami": 50}'::jsonb, '["HUD Form 52517 (Application)", "Photo ID for all household members", "Social Security cards", "Birth certificates", "Income verification", "Rental history", "Criminal background check consent"]'::jsonb, 'https://www.hud.gov/topics/housing_choice_voucher_program_section_8', 'https://www.hud.gov/topics/housing_choice_voucher_program_section_8', '["HUD-52517"]'::jsonb, 180, 'hud-section-8-housing-choice-voucher')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('USDA Single Family Housing Direct Loan Program (Section 502)', 'USDA Rural Development', 'individual', 'housing', 'This program assists low- and very-low-income applicants in obtaining decent, safe, and sanitary housing in eligible rural areas by providing payment assistance to reduce the applicant''s repayment obligation. Payment assistance is a type of subsidy that reduces the mortgage payment temporarily for a period of time. The amount of assistance is determined by the adjusted family income.', 500000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "requires_rural_location": true, "max_household_income_percent_ami": 80}'::jsonb, '["USDA Form RD 410-4", "Proof of income", "Credit history", "Property appraisal", "Title search", "Flood determination"]'::jsonb, 'https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-direct-home-loans', 'https://www.rd.usda.gov', '[]'::jsonb, 60, 'usda-section-502-direct-loan')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HOME Investment Partnerships Program', 'U.S. Department of Housing and Urban Development', 'individual', 'housing', 'The HOME Investment Partnerships Program provides formula grants to states and localities that communities use to fund a wide range of activities including building, buying, and/or rehabilitating affordable housing for rent or homeownership or providing direct rental assistance to low-income people. It is the largest federal block grant to state and local governments for housing.', 15000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "max_household_income_percent_ami": 80}'::jsonb, '["Local PHA application", "Income documentation", "Asset verification", "Rental history", "Photo ID"]'::jsonb, 'https://www.hud.gov/program_offices/comm_planning/home', 'https://www.hud.gov/program_offices/comm_planning/home', '[]'::jsonb, 90, 'home-investment-partnerships-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Low Income Home Energy Assistance Program (LIHEAP)', 'U.S. Department of Health and Human Services', 'individual', 'housing', 'LIHEAP helps low-income households with their home energy costs including heating, cooling, and crisis assistance. The program also helps with weatherization to reduce energy consumption. Benefits are provided as cash or vendor payments and are administered by states, territories, and tribal governments through local community action agencies.', 1000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "max_household_income_percent_poverty": 150}'::jsonb, '["State application form", "Proof of income (30 days)", "Utility bills", "Photo ID", "Proof of address", "Social Security numbers for all household members"]'::jsonb, 'https://www.benefits.gov/benefit/623', 'https://www.acf.hhs.gov/ocs/programs/liheap', '[]'::jsonb, 30, 'liheap-energy-assistance')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HUD Continuum of Care Program', 'U.S. Department of Housing and Urban Development', 'individual', 'housing', 'The Continuum of Care (CoC) program promotes community-wide commitment to the goal of ending homelessness. It provides funding for efforts by nonprofit providers and State and local governments to quickly rehouse homeless individuals and families while minimizing trauma and dislocation. The program provides transitional housing, permanent supportive housing, and rapid rehousing.', 20000, TRUE, NULL, '{"requires_us_citizen": true, "requires_homeless_or_at_risk": true}'::jsonb, '["Local CoC application", "Proof of homelessness or housing instability", "Income documentation", "Photo ID"]'::jsonb, 'https://www.hud.gov/program_offices/comm_planning/continuum_of_care', 'https://www.hud.gov/program_offices/comm_planning/continuum_of_care', '[]'::jsonb, 60, 'hud-continuum-of-care-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('USDA Rural Housing Repair Loans and Grants (Section 504)', 'USDA Rural Development', 'individual', 'housing', 'The Section 504 Home Repair program provides loans and grants to very-low-income homeowners to repair, improve, or modernize their homes or to remove health and safety hazards. Grants are provided to elderly (age 62+) very-low-income homeowners. The program is available only in eligible rural areas and helps homeowners who cannot afford commercial financing.', 10000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "requires_rural_location": true, "min_age": 62, "requires_homeowner": true}'::jsonb, '["USDA Form RD 410-4", "Proof of ownership", "Income documentation", "Proof of occupancy", "Contractor estimates"]'::jsonb, 'https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants', 'https://www.rd.usda.gov', '[]'::jsonb, 60, 'usda-section-504-home-repair')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HUD Community Development Block Grant (CDBG)', 'U.S. Department of Housing and Urban Development', 'small_business', 'housing', 'The Community Development Block Grant (CDBG) program is one of the longest-running HUD programs. It provides annual grants on a formula basis to states, cities, and counties to develop viable urban communities by providing decent housing, a suitable living environment, and expanding economic opportunities, principally for low- and moderate-income persons.', 3000000, TRUE, NULL, '{"requires_us_organization": true, "requires_low_moderate_income_service": true}'::jsonb, '["Local government application", "Needs assessment", "Program description", "Budget narrative", "Organizational capacity documentation"]'::jsonb, 'https://www.hud.gov/program_offices/comm_planning/cdbg', 'https://www.hud.gov/program_offices/comm_planning/cdbg', '[]'::jsonb, 120, 'hud-community-development-block-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NeighborWorks America Homeownership Grant', 'NeighborWorks America', 'individual', 'housing', 'NeighborWorks America and its network of nearly 250 local nonprofit organizations provide down payment assistance, closing cost assistance, and homebuyer education for low- and moderate-income first-time homebuyers. Programs vary by location but typically help buyers purchase homes in targeted neighborhoods and communities across the U.S.', 10000, TRUE, NULL, '{"requires_us_citizen": true, "requires_first_time_homebuyer": true, "requires_low_moderate_income": true, "max_household_income_percent_ami": 120}'::jsonb, '["Local NeighborWorks application", "Homebuyer education certificate", "Income documentation", "Credit report", "Mortgage pre-approval letter"]'::jsonb, 'https://www.neighborworks.org/find-a-location', 'https://www.neighborworks.org', '[]'::jsonb, 30, 'neighborworks-homeownership-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Emergency Solutions Grant Program (ESG)', 'U.S. Department of Housing and Urban Development', 'individual', 'housing', 'The Emergency Solutions Grants (ESG) program provides funds to engage homeless individuals and families living on the street, improve the number and quality of emergency shelters, help operate emergency shelters, provide essential services to shelter residents, rapidly rehouse homeless individuals and families, and prevent families and individuals from becoming homeless.', 12000, TRUE, NULL, '{"requires_us_citizen": true, "requires_homeless_or_at_risk": true}'::jsonb, '["Local ESG application", "Proof of housing crisis", "Income documentation", "Photo ID"]'::jsonb, 'https://www.hud.gov/program_offices/comm_planning/esg', 'https://www.hud.gov/program_offices/comm_planning/esg', '[]'::jsonb, 30, 'emergency-solutions-grant-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HUD Choice Neighborhoods Initiative', 'U.S. Department of Housing and Urban Development', 'small_business', 'housing', 'The Choice Neighborhoods Initiative supports locally driven strategies to address struggling neighborhoods with distressed public or HUD-assisted housing through a comprehensive approach to neighborhood transformation. Planning grants help communities develop comprehensive neighborhood revitalization plans. Implementation grants fund the full execution of these plans.', 50000000, TRUE, '2026-03-01', '{"requires_local_government": true, "requires_distressed_neighborhood": true}'::jsonb, '["Federal application (Grants.gov)", "Transformation plan", "Community needs assessment", "Partnership letters", "Budget narrative", "Performance metrics"]'::jsonb, 'https://www.hud.gov/program_offices/public_indian_housing/programs/ph/cn', 'https://www.hud.gov/program_offices/public_indian_housing/programs/ph/cn', '[]'::jsonb, 180, 'hud-choice-neighborhoods-initiative')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('DOE Weatherization Assistance Program (WAP)', 'U.S. Department of Energy', 'individual', 'energy', 'The Weatherization Assistance Program (WAP) reduces energy costs for low-income households by increasing the energy efficiency of their homes, while ensuring their health and safety. Funded through the DOE, WAP provides services to approximately 35,000 homes per year. Services include insulation, air sealing, HVAC system upgrades, and health and safety improvements.', 8000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "max_household_income_percent_poverty": 200}'::jsonb, '["State application form", "Proof of income", "Utility bills", "Proof of residence", "Photo ID"]'::jsonb, 'https://www.energy.gov/scep/wap/weatherization-assistance-program', 'https://www.energy.gov/scep/wap/weatherization-assistance-program', '[]'::jsonb, 60, 'doe-weatherization-assistance-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('USDA Rural Energy for America Program (REAP)', 'USDA Rural Development', 'small_business', 'energy', 'REAP provides guaranteed loan financing and grant funding to agricultural producers and rural small businesses for renewable energy systems or to make energy efficiency improvements. Renewable energy systems include wind, solar, biomass, geothermal, hydroelectric, and hydrogen systems. The program also funds energy efficiency improvements to existing buildings, equipment, and facilities.', 500000, TRUE, '2026-03-31', '{"requires_us_business": true, "requires_rural_location": true, "requires_agricultural_producer_or_rural_small_business": true}'::jsonb, '["SF 424 Application", "Energy audit or assessment", "Project technical report", "Financial statements", "Business plan", "Environmental review documentation"]'::jsonb, 'https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans', 'https://www.rd.usda.gov', '[]'::jsonb, 90, 'usda-rural-energy-for-america-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('DOE State Energy Program (SEP)', 'U.S. Department of Energy', 'small_business', 'energy', 'The State Energy Program (SEP) provides funding and technical assistance to states and territories for developing and implementing state-specific energy initiatives. SEP funds a wide range of activities including renewable energy deployment, energy efficiency improvements, transportation sector initiatives, and energy planning. Grants flow from DOE to states, who then issue sub-grants to businesses and organizations.', 250000, TRUE, NULL, '{"requires_us_business": true, "requires_energy_project": true}'::jsonb, '["State SEP application", "Project description", "Budget narrative", "Technical specifications", "Energy savings analysis"]'::jsonb, 'https://www.energy.gov/scep/slsc/state-energy-program', 'https://www.energy.gov/scep/slsc/state-energy-program', '[]'::jsonb, 90, 'doe-state-energy-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Inflation Reduction Act Home Energy Rebates (HOMES Program)', 'U.S. Department of Energy', 'individual', 'energy', 'The HOMES (Home Owner Managing Energy Savings) Rebate Program provides rebates to homeowners who make whole-home energy efficiency upgrades. The rebate amount is based on modeled or measured energy savings and household income. Low- and moderate-income households can receive higher rebate amounts. Rebates are administered through state energy offices.', 8000, TRUE, NULL, '{"requires_us_citizen": true, "requires_homeowner": true, "requires_energy_upgrade": true}'::jsonb, '["State rebate application", "Proof of homeownership", "Energy audit", "Contractor invoices", "Income documentation (for enhanced rebates)"]'::jsonb, 'https://www.energy.gov/scep/home-energy-rebates-frequently-asked-questions', 'https://www.energy.gov/scep/home-energy-rebates-programs', '[]'::jsonb, 30, 'ira-homes-rebate-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Inflation Reduction Act High-Efficiency Electric Home Rebate (HEEHRA)', 'U.S. Department of Energy', 'individual', 'energy', 'The High-Efficiency Electric Home Rebate Act (HEEHRA) provides point-of-sale rebates for low- and moderate-income households to electrify their homes. Rebates cover heat pumps, heat pump water heaters, electric stoves, clothes dryers, insulation, weatherization, and electrical panel upgrades. Income-qualified households can receive up to $14,000 in rebates.', 14000, TRUE, NULL, '{"requires_us_citizen": true, "requires_homeowner_or_renter": true, "max_household_income_percent_ami": 150}'::jsonb, '["State rebate application", "Income documentation", "Product receipts", "Contractor installation documentation"]'::jsonb, 'https://www.energy.gov/scep/home-energy-rebates-frequently-asked-questions', 'https://www.energy.gov/scep/home-energy-rebates-programs', '[]'::jsonb, 30, 'ira-heehra-rebate-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('EPA Clean School Bus Program', 'U.S. Environmental Protection Agency', 'small_business', 'energy', 'The Clean School Bus program provides up to $5 billion over five years to replace existing school buses with zero-emission and clean school buses. Priority is given to high-need local education agencies, rural local education agencies, and tribal schools. Grants and rebates fund the purchase of new electric and propane buses to replace older, higher-polluting diesel buses.', 400000, TRUE, '2026-04-30', '{"requires_school_district": true, "requires_existing_diesel_bus": true}'::jsonb, '["Grants.gov application", "Fleet inventory documentation", "Replacement plan", "Budget narrative", "Priority community documentation"]'::jsonb, 'https://www.epa.gov/cleanschoolbus', 'https://www.epa.gov/cleanschoolbus', '[]'::jsonb, 90, 'epa-clean-school-bus-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('DOE Solar for All Program', 'U.S. Department of Energy', 'individual', 'energy', 'Solar for All is a $7 billion program funded by the Inflation Reduction Act that provides grants to states, territories, Tribal governments, and nonprofits to deploy rooftop solar and community solar to low-income and disadvantaged communities. The program aims to enable 900,000+ households to benefit from solar energy and lower their electricity bills through direct incentives and rebates.', 5000, TRUE, NULL, '{"requires_us_citizen": true, "requires_low_income": true, "max_household_income_percent_ami": 80}'::jsonb, '["State/program application", "Income documentation", "Utility bills", "Proof of residence"]'::jsonb, 'https://www.epa.gov/greenhouse-gas-reduction-fund/solar-all', 'https://www.epa.gov/greenhouse-gas-reduction-fund/solar-all', '[]'::jsonb, 60, 'doe-solar-for-all-program')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('USDA Biorefinery, Renewable Chemical, and Biobased Product Manufacturing Grant', 'USDA Rural Development', 'small_business', 'energy', 'This program assists in the development of new and emerging technologies for advanced biofuels, renewable chemicals, and biobased product manufacturing so as to materially enhance the nation''s economic security, create domestic jobs, and protect the environment. Grants assist in developing new and emerging technologies or retrofitting existing facilities.', 15000000, TRUE, '2026-02-28', '{"requires_us_business": true, "requires_rural_location": true, "requires_biorefinery_project": true}'::jsonb, '["SF 424 Application", "Technical feasibility study", "Business plan", "Environmental review", "Financial statements", "Project timeline"]'::jsonb, 'https://www.rd.usda.gov/programs-services/energy-programs/biorefinery-renewable-chemical-and-biobased-product-manufacturing-assistance', 'https://www.rd.usda.gov', '[]'::jsonb, 120, 'usda-biorefinery-biobased-product-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('DOE Energy Efficiency and Conservation Block Grant (EECBG)', 'U.S. Department of Energy', 'small_business', 'energy', 'The Energy Efficiency and Conservation Block Grant (EECBG) Program assists eligible entities in implementing strategies to reduce fossil fuel emissions, reduce total energy use, and improve energy efficiency in the transportation, building, and other sectors. The program provides formula-based grants to states, territories, local governments, and Indian tribes.', 1000000, TRUE, NULL, '{"requires_local_government": true, "requires_energy_efficiency_project": true}'::jsonb, '["Federal application", "Energy efficiency plan", "Budget narrative", "Technical specifications", "Environmental review"]'::jsonb, 'https://www.energy.gov/scep/slsc/energy-efficiency-and-conservation-block-grant-program', 'https://www.energy.gov/scep/slsc/energy-efficiency-and-conservation-block-grant-program', '[]'::jsonb, 90, 'doe-energy-efficiency-conservation-block-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('NIH Small Business Innovation Research (SBIR) – Health', 'National Institutes of Health', 'small_business', 'health', 'NIH SBIR grants support domestic small businesses engaged in research and development with high technological innovation potential in areas of importance to public health. Phase I awards provide up to $300,000 for feasibility research. Phase II awards provide up to $1 million for full R&D. The program stimulates commercialization of innovations stemming from federal research and development.', 1000000, TRUE, '2026-04-05', '{"requires_us_business": true, "requires_small_business": true, "max_employees": 500, "requires_us_ownership": true, "requires_health_focus": true}'::jsonb, '["SF 424 Application", "Research strategy (12 pages)", "Budget justification", "Facilities and resources", "Human subjects research plan", "Biosketches for key personnel", "Letters of support"]'::jsonb, 'https://grants.nih.gov/grants/funding/sbir.htm', 'https://www.nih.gov', '[]'::jsonb, 180, 'nih-sbir-health')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HRSA Federally Qualified Health Center (FQHC) Grant', 'Health Resources and Services Administration', 'small_business', 'health', 'HRSA''s Health Center Program provides grants to community-based organizations to become Federally Qualified Health Centers (FQHCs), which provide comprehensive primary care services to underserved communities regardless of patients'' ability to pay. FQHCs receive enhanced Medicaid and Medicare reimbursements and access to the Federal Tort Claims Act malpractice coverage.', 650000, TRUE, '2026-05-01', '{"requires_us_nonprofit": true, "requires_health_organization": true, "requires_underserved_community_service": true}'::jsonb, '["HRSA Electronic Handbook application", "Needs assessment", "Service area documentation", "Governance documentation", "Financial statements", "Operational plan", "Community health needs assessment"]'::jsonb, 'https://bphc.hrsa.gov/funding/apply-for-funding', 'https://bphc.hrsa.gov', '[]'::jsonb, 180, 'hrsa-federally-qualified-health-center-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('CDC Community Health Worker Training Grant', 'Centers for Disease Control and Prevention', 'small_business', 'health', 'CDC provides grants to train and deploy Community Health Workers (CHWs) who serve as a bridge between health and social services and the community. CHW programs improve health outcomes for underserved populations by addressing social determinants of health, promoting preventive care, and helping individuals navigate health and social service systems.', 500000, TRUE, '2026-04-01', '{"requires_us_nonprofit": true, "requires_health_organization": true}'::jsonb, '["CDC PODS application", "Program narrative", "Logic model", "Budget justification", "Evaluation plan", "Partnership letters"]'::jsonb, 'https://www.cdc.gov/grants/index.html', 'https://www.cdc.gov', '[]'::jsonb, 120, 'cdc-community-health-worker-training-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('SAMHSA Substance Abuse Prevention and Treatment Block Grant', 'Substance Abuse and Mental Health Services Administration', 'small_business', 'health', 'SAMHSA''s Substance Abuse Prevention and Treatment (SAPT) Block Grant provides funds to states and territories for substance use disorder prevention, treatment, and recovery support services. States allocate funds to local providers of prevention activities, treatment services, and recovery supports for individuals with substance use disorders.', 750000, TRUE, NULL, '{"requires_us_nonprofit": true, "requires_substance_abuse_services": true}'::jsonb, '["State SAMHSA application", "Program description", "Budget", "Performance measures", "Organizational capacity documentation"]'::jsonb, 'https://www.samhsa.gov/grants', 'https://www.samhsa.gov', '[]'::jsonb, 90, 'samhsa-substance-abuse-prevention-treatment-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Susan G. Komen Breast Cancer Research Grant', 'Susan G. Komen Foundation', 'individual', 'health', 'Susan G. Komen funds a variety of research grants focused on breast cancer prevention, detection, and treatment. The foundation provides grants to researchers at all career stages, from graduate students to experienced investigators. Komen has invested more than $1 billion in breast cancer research since 1982, making it one of the largest funders of breast cancer research.', 250000, TRUE, '2026-02-01', '{"requires_us_researcher": true, "requires_breast_cancer_research": true}'::jsonb, '["Online application", "Research proposal", "Budget justification", "Biosketches for key personnel", "Institution sign-off", "IRB/IACUC documentation"]'::jsonb, 'https://www.komen.org/research/grant-opportunities/', 'https://www.komen.org', '[]'::jsonb, 180, 'susan-g-komen-breast-cancer-research-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('American Heart Association Innovative Project Award', 'American Heart Association', 'individual', 'health', 'The AHA Innovative Project Award provides funding for pioneering research in cardiovascular disease and stroke. Awards support high-risk, high-reward projects that may not fit traditional funding mechanisms. The program encourages innovative approaches and novel hypotheses that have the potential to transform understanding of cardiovascular and cerebrovascular disease.', 200000, TRUE, '2026-03-01', '{"requires_us_researcher": true, "requires_cardiovascular_research": true, "requires_institutional_affiliation": true}'::jsonb, '["Online application (Grants@Heart)", "Research proposal (5 pages)", "Budget", "Biosketches", "Institutional letter", "Lay summary"]'::jsonb, 'https://professional.heart.org/en/research-programs/application-information', 'https://www.heart.org', '[]'::jsonb, 120, 'american-heart-association-innovative-project-award')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('Robert Wood Johnson Foundation Health Policy Fellowship', 'Robert Wood Johnson Foundation', 'individual', 'health', 'The Robert Wood Johnson Foundation Health Policy Fellowship places mid-career health professionals in leadership positions in Congress or the Executive Branch for a year of experiential learning in the health policy arena. Fellows gain firsthand experience in the federal policy process and build lasting relationships that enhance their capacity to improve health and health care.', 120000, TRUE, '2025-10-01', '{"requires_us_citizen": true, "requires_health_professional": true, "requires_mid_career": true}'::jsonb, '["Online application", "Curriculum vitae", "Personal statement", "Letters of reference (3)", "Academic transcripts"]'::jsonb, 'https://www.rwjf.org/en/grants/active-funding-opportunities/2023/rwjf-health-policy-fellows.html', 'https://www.rwjf.org', '[]'::jsonb, 120, 'rwjf-health-policy-fellowship')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('W.K. Kellogg Foundation Health Equity Grant', 'W.K. Kellogg Foundation', 'small_business', 'health', 'The W.K. Kellogg Foundation funds organizations working to advance racial equity and health equity for vulnerable children and families. Grants support community health programs, policy advocacy, and systems change initiatives that address the root causes of health disparities. The foundation focuses on food security, mental health, and access to quality healthcare.', 500000, TRUE, '2026-02-15', '{"requires_us_nonprofit": true, "requires_health_equity_focus": true}'::jsonb, '["Online letter of inquiry", "Organization description", "Program description", "Budget overview", "IRS determination letter", "Annual report"]'::jsonb, 'https://www.wkkf.org/grants/grant-application', 'https://www.wkkf.org', '[]'::jsonb, 180, 'wk-kellogg-health-equity-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('CDC Rural Health Grant', 'Centers for Disease Control and Prevention', 'small_business', 'health', 'CDC''s Rural Health program funds initiatives to improve the health of rural populations who often face greater challenges accessing quality health care. Grants support telehealth infrastructure, rural health workforce development, chronic disease prevention, maternal and child health, and behavioral health programs in rural communities across the United States.', 300000, TRUE, '2026-04-30', '{"requires_us_nonprofit": true, "requires_rural_service_area": true, "requires_health_organization": true}'::jsonb, '["Grants.gov application", "Project narrative", "Logic model", "Budget justification", "Evaluation plan", "Rural community documentation"]'::jsonb, 'https://www.cdc.gov/grants/index.html', 'https://www.cdc.gov/ruralhealth/', '[]'::jsonb, 120, 'cdc-rural-health-grant')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO grants (name, agency, category, subcategory, description, max_amount, is_recurring, deadline, eligibility_criteria, required_documents, application_url, official_source_url, form_numbers, processing_time_days, slug)
VALUES ('HRSA Maternal and Child Health Block Grant', 'Health Resources and Services Administration', 'small_business', 'health', 'The Maternal and Child Health (MCH) Block Grant provides federal funds to states and territories to improve the health of mothers, children, and their families. Programs funded include prenatal care, newborn screening, immunizations, early intervention services, child health outreach, and programs for children and youth with special health care needs.', 1000000, TRUE, NULL, '{"requires_us_state_agency": true, "requires_maternal_child_health_focus": true}'::jsonb, '["HRSA Electronic Handbook application", "State MCH needs assessment", "Annual report", "Performance measures", "Budget narrative"]'::jsonb, 'https://mchb.hrsa.gov/programs-impact/programs/maternal-child-health-block-grant', 'https://mchb.hrsa.gov', '[]'::jsonb, 120, 'hrsa-maternal-child-health-block-grant')
ON CONFLICT (slug) DO NOTHING;

