// 2024 HUD Area Median Income (AMI) data
// Source: HUD FY2024 Income Limits
// Organized by state code → list of {name, ami (4-person household)}

export interface AreaAMI {
  name: string
  ami: number // 4-person household AMI
}

export const AMI_BY_STATE: Record<string, AreaAMI[]> = {
  AL: [
    { name: "Statewide average", ami: 75_500 },
    { name: "Birmingham metro", ami: 85_200 },
    { name: "Huntsville metro", ami: 92_400 },
    { name: "Mobile metro", ami: 72_100 },
    { name: "Montgomery metro", ami: 78_300 },
  ],
  AK: [
    { name: "Statewide average", ami: 104_400 },
    { name: "Anchorage metro", ami: 107_200 },
    { name: "Fairbanks metro", ami: 102_600 },
  ],
  AZ: [
    { name: "Statewide average", ami: 84_400 },
    { name: "Phoenix-Mesa metro", ami: 88_500 },
    { name: "Tucson metro", ami: 76_200 },
    { name: "Flagstaff metro", ami: 82_100 },
  ],
  AR: [
    { name: "Statewide average", ami: 67_300 },
    { name: "Little Rock metro", ami: 77_400 },
    { name: "Fayetteville metro", ami: 80_200 },
  ],
  CA: [
    { name: "Statewide average", ami: 106_700 },
    { name: "Los Angeles metro", ami: 98_900 },
    { name: "San Francisco metro", ami: 171_000 },
    { name: "San Jose metro", ami: 187_900 },
    { name: "San Diego metro", ami: 114_200 },
    { name: "Sacramento metro", ami: 101_600 },
    { name: "Fresno metro", ami: 76_200 },
    { name: "Riverside-San Bernardino", ami: 90_300 },
    { name: "Oakland metro", ami: 171_000 },
    { name: "Bakersfield metro", ami: 71_400 },
  ],
  CO: [
    { name: "Statewide average", ami: 101_100 },
    { name: "Denver-Aurora metro", ami: 118_100 },
    { name: "Colorado Springs metro", ami: 93_900 },
    { name: "Boulder metro", ami: 127_400 },
    { name: "Fort Collins metro", ami: 105_400 },
  ],
  CT: [
    { name: "Statewide average", ami: 104_100 },
    { name: "Hartford metro", ami: 104_700 },
    { name: "New Haven metro", ami: 97_300 },
    { name: "Bridgeport-Stamford metro", ami: 126_300 },
  ],
  DE: [
    { name: "Statewide average", ami: 93_900 },
    { name: "Dover metro", ami: 85_200 },
    { name: "Philadelphia area (DE portion)", ami: 105_000 },
  ],
  FL: [
    { name: "Statewide average", ami: 82_000 },
    { name: "Miami-Fort Lauderdale metro", ami: 80_800 },
    { name: "Orlando metro", ami: 82_800 },
    { name: "Tampa-St. Petersburg metro", ami: 85_900 },
    { name: "Jacksonville metro", ami: 88_200 },
    { name: "Naples metro", ami: 95_400 },
    { name: "Palm Beach metro", ami: 91_200 },
  ],
  GA: [
    { name: "Statewide average", ami: 85_500 },
    { name: "Atlanta metro", ami: 106_100 },
    { name: "Savannah metro", ami: 79_500 },
    { name: "Augusta metro", ami: 74_800 },
    { name: "Columbus metro", ami: 69_900 },
  ],
  HI: [
    { name: "Statewide average", ami: 109_900 },
    { name: "Honolulu metro", ami: 114_200 },
    { name: "Maui County", ami: 102_000 },
  ],
  ID: [
    { name: "Statewide average", ami: 80_700 },
    { name: "Boise metro", ami: 89_000 },
    { name: "Coeur d'Alene metro", ami: 80_000 },
  ],
  IL: [
    { name: "Statewide average", ami: 92_100 },
    { name: "Chicago metro", ami: 106_300 },
    { name: "Springfield metro", ami: 84_900 },
    { name: "Rockford metro", ami: 79_500 },
    { name: "Peoria metro", ami: 84_200 },
  ],
  IN: [
    { name: "Statewide average", ami: 78_200 },
    { name: "Indianapolis metro", ami: 91_400 },
    { name: "Fort Wayne metro", ami: 81_200 },
    { name: "Evansville metro", ami: 75_600 },
    { name: "South Bend metro", ami: 77_800 },
  ],
  IA: [
    { name: "Statewide average", ami: 84_000 },
    { name: "Des Moines metro", ami: 96_500 },
    { name: "Cedar Rapids metro", ami: 87_300 },
    { name: "Iowa City metro", ami: 95_400 },
  ],
  KS: [
    { name: "Statewide average", ami: 82_000 },
    { name: "Wichita metro", ami: 81_700 },
    { name: "Kansas City area (KS)", ami: 101_600 },
  ],
  KY: [
    { name: "Statewide average", ami: 72_000 },
    { name: "Louisville metro", ami: 86_700 },
    { name: "Lexington metro", ami: 85_200 },
  ],
  LA: [
    { name: "Statewide average", ami: 70_400 },
    { name: "New Orleans metro", ami: 75_700 },
    { name: "Baton Rouge metro", ami: 80_200 },
    { name: "Shreveport metro", ami: 69_800 },
  ],
  ME: [
    { name: "Statewide average", ami: 85_700 },
    { name: "Portland metro", ami: 101_300 },
    { name: "Bangor metro", ami: 80_000 },
  ],
  MD: [
    { name: "Statewide average", ami: 116_300 },
    { name: "Baltimore metro", ami: 115_600 },
    { name: "Washington DC metro (MD)", ami: 152_400 },
    { name: "Salisbury metro", ami: 87_800 },
  ],
  MA: [
    { name: "Statewide average", ami: 115_000 },
    { name: "Boston metro", ami: 138_600 },
    { name: "Springfield metro", ami: 90_200 },
    { name: "Worcester metro", ami: 107_300 },
    { name: "Barnstable (Cape Cod)", ami: 112_000 },
  ],
  MI: [
    { name: "Statewide average", ami: 83_400 },
    { name: "Detroit metro", ami: 94_600 },
    { name: "Grand Rapids metro", ami: 92_700 },
    { name: "Ann Arbor metro", ami: 115_900 },
    { name: "Lansing metro", ami: 85_300 },
  ],
  MN: [
    { name: "Statewide average", ami: 99_600 },
    { name: "Minneapolis-St. Paul metro", ami: 117_600 },
    { name: "Duluth metro", ami: 86_400 },
    { name: "Rochester metro", ami: 108_700 },
  ],
  MS: [
    { name: "Statewide average", ami: 63_900 },
    { name: "Jackson metro", ami: 70_400 },
    { name: "Gulfport metro", ami: 66_500 },
  ],
  MO: [
    { name: "Statewide average", ami: 79_100 },
    { name: "Kansas City metro", ami: 98_700 },
    { name: "St. Louis metro", ami: 95_400 },
    { name: "Springfield metro", ami: 73_200 },
  ],
  MT: [
    { name: "Statewide average", ami: 80_800 },
    { name: "Billings metro", ami: 85_100 },
    { name: "Missoula metro", ami: 83_200 },
    { name: "Great Falls metro", ami: 74_900 },
  ],
  NE: [
    { name: "Statewide average", ami: 87_200 },
    { name: "Omaha metro", ami: 97_900 },
    { name: "Lincoln metro", ami: 89_600 },
  ],
  NV: [
    { name: "Statewide average", ami: 83_100 },
    { name: "Las Vegas metro", ami: 82_100 },
    { name: "Reno metro", ami: 91_500 },
  ],
  NH: [
    { name: "Statewide average", ami: 108_500 },
    { name: "Manchester metro", ami: 110_900 },
    { name: "Nashua metro", ami: 117_200 },
  ],
  NJ: [
    { name: "Statewide average", ami: 115_900 },
    { name: "Newark metro", ami: 119_400 },
    { name: "Atlantic City metro", ami: 89_700 },
    { name: "Trenton metro", ami: 110_300 },
  ],
  NM: [
    { name: "Statewide average", ami: 70_200 },
    { name: "Albuquerque metro", ami: 79_800 },
    { name: "Santa Fe metro", ami: 88_900 },
    { name: "Las Cruces metro", ami: 62_100 },
  ],
  NY: [
    { name: "Statewide average", ami: 96_400 },
    { name: "New York City (5 boroughs)", ami: 120_700 },
    { name: "Long Island (Nassau/Suffolk)", ami: 141_800 },
    { name: "Buffalo metro", ami: 80_800 },
    { name: "Rochester metro", ami: 84_200 },
    { name: "Albany metro", ami: 99_200 },
    { name: "Syracuse metro", ami: 81_900 },
  ],
  NC: [
    { name: "Statewide average", ami: 80_200 },
    { name: "Charlotte metro", ami: 97_300 },
    { name: "Raleigh metro", ami: 107_800 },
    { name: "Durham metro", ami: 100_900 },
    { name: "Greensboro metro", ami: 79_400 },
    { name: "Winston-Salem metro", ami: 78_100 },
  ],
  ND: [
    { name: "Statewide average", ami: 88_200 },
    { name: "Fargo metro", ami: 93_600 },
    { name: "Bismarck metro", ami: 94_100 },
  ],
  OH: [
    { name: "Statewide average", ami: 80_400 },
    { name: "Columbus metro", ami: 96_600 },
    { name: "Cleveland metro", ami: 84_700 },
    { name: "Cincinnati metro", ami: 94_100 },
    { name: "Dayton metro", ami: 83_500 },
    { name: "Toledo metro", ami: 77_700 },
    { name: "Akron metro", ami: 80_300 },
  ],
  OK: [
    { name: "Statewide average", ami: 73_400 },
    { name: "Oklahoma City metro", ami: 82_400 },
    { name: "Tulsa metro", ami: 82_900 },
  ],
  OR: [
    { name: "Statewide average", ami: 92_500 },
    { name: "Portland metro", ami: 109_100 },
    { name: "Salem metro", ami: 85_600 },
    { name: "Eugene metro", ami: 84_500 },
    { name: "Bend metro", ami: 98_300 },
  ],
  PA: [
    { name: "Statewide average", ami: 87_500 },
    { name: "Philadelphia metro", ami: 105_700 },
    { name: "Pittsburgh metro", ami: 91_900 },
    { name: "Allentown metro", ami: 91_400 },
    { name: "Harrisburg metro", ami: 91_900 },
  ],
  RI: [
    { name: "Statewide average", ami: 97_300 },
    { name: "Providence metro", ami: 97_500 },
  ],
  SC: [
    { name: "Statewide average", ami: 76_500 },
    { name: "Columbia metro", ami: 83_400 },
    { name: "Charleston metro", ami: 92_400 },
    { name: "Greenville metro", ami: 85_200 },
  ],
  SD: [
    { name: "Statewide average", ami: 82_100 },
    { name: "Sioux Falls metro", ami: 90_800 },
    { name: "Rapid City metro", ami: 84_200 },
  ],
  TN: [
    { name: "Statewide average", ami: 79_000 },
    { name: "Nashville metro", ami: 101_400 },
    { name: "Memphis metro", ami: 75_700 },
    { name: "Knoxville metro", ami: 82_900 },
    { name: "Chattanooga metro", ami: 80_900 },
  ],
  TX: [
    { name: "Statewide average", ami: 87_000 },
    { name: "Austin metro", ami: 113_300 },
    { name: "Dallas-Fort Worth metro", ami: 105_400 },
    { name: "Houston metro", ami: 96_100 },
    { name: "San Antonio metro", ami: 84_900 },
    { name: "El Paso metro", ami: 66_500 },
    { name: "Lubbock metro", ami: 74_200 },
    { name: "McAllen metro", ami: 52_800 },
  ],
  UT: [
    { name: "Statewide average", ami: 100_900 },
    { name: "Salt Lake City metro", ami: 108_500 },
    { name: "Provo-Orem metro", ami: 103_900 },
    { name: "Ogden metro", ami: 102_700 },
    { name: "St. George metro", ami: 84_800 },
  ],
  VT: [
    { name: "Statewide average", ami: 91_800 },
    { name: "Burlington metro", ami: 99_700 },
  ],
  VA: [
    { name: "Statewide average", ami: 104_000 },
    { name: "Washington DC metro (VA)", ami: 152_400 },
    { name: "Richmond metro", ami: 101_800 },
    { name: "Virginia Beach metro", ami: 95_100 },
    { name: "Roanoke metro", ami: 80_700 },
  ],
  WA: [
    { name: "Statewide average", ami: 112_800 },
    { name: "Seattle-Bellevue metro", ami: 145_500 },
    { name: "Spokane metro", ami: 84_500 },
    { name: "Tacoma metro", ami: 110_800 },
    { name: "Olympia metro", ami: 107_100 },
  ],
  WV: [
    { name: "Statewide average", ami: 65_100 },
    { name: "Charleston metro", ami: 71_500 },
    { name: "Huntington metro", ami: 63_200 },
  ],
  WI: [
    { name: "Statewide average", ami: 87_800 },
    { name: "Milwaukee metro", ami: 90_400 },
    { name: "Madison metro", ami: 107_800 },
    { name: "Green Bay metro", ami: 86_800 },
  ],
  WY: [
    { name: "Statewide average", ami: 85_600 },
    { name: "Cheyenne metro", ami: 88_700 },
    { name: "Casper metro", ami: 84_200 },
  ],
  DC: [
    { name: "Washington DC / District", ami: 152_400 },
  ],
}

export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "Washington DC" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
]
