/**
 * State-specific application URLs for programs administered at the state/local level.
 * Key = grant slug. Value = map of 2-letter state code → exact apply URL.
 */
export const STATE_APPLY_URLS: Record<string, Record<string, string>> = {

  // ── SNAP ────────────────────────────────────────────────────────────────────
  "snap-benefits": {
    AL: "https://aces.dhr.alabama.gov",
    AK: "https://dhss.alaska.gov/dpa/Pages/foodstamps/default.aspx",
    AZ: "https://healthearizonaplus.gov",
    AR: "https://access.arkansas.gov",
    CA: "https://benefitscal.com",
    CO: "https://coloradopeak.secure.force.com",
    CT: "https://www.connect.ct.gov",
    DE: "https://assist.dhss.delaware.gov",
    DC: "https://dhs.dc.gov/service/snap-benefits",
    FL: "https://access.florida.gov",
    GA: "https://dfcs.georgia.gov/snap",
    HI: "https://pais.dhs.hawaii.gov",
    ID: "https://healthandwelfare.idaho.gov/services/food-assistance/snap",
    IL: "https://abe.illinois.gov",
    IN: "https://www.in.gov/fssa/dfr/snap",
    IA: "https://dhs.iowa.gov/food-assistance",
    KS: "https://www.kansasbenefits.org",
    KY: "https://kynect.ky.gov",
    LA: "https://dcfs.louisiana.gov/snap",
    ME: "https://www.maine.gov/dhhs/ofi/programs-services/snap",
    MD: "https://mymdthink.maryland.gov",
    MA: "https://dtaconnect.eohhs.mass.gov/apply",
    MI: "https://mibridges.michigan.gov",
    MN: "https://mnbenefits.mn.gov",
    MS: "https://www.mdhs.ms.gov/economic-assistance/snap",
    MO: "https://mydss.mo.gov",
    MT: "https://dphhs.mt.gov/PHSD/snap",
    NE: "https://dhhs.ne.gov/Pages/Food-Assistance.aspx",
    NV: "https://dwss.nv.gov",
    NH: "https://nheasy.nh.gov",
    NJ: "https://www.njhelps.org",
    NM: "https://www.hsd.state.nm.us/snap",
    NY: "https://mybenefits.ny.gov",
    NC: "https://epass.nc.gov",
    ND: "https://www.hhs.nd.gov/economic-assistance/snap",
    OH: "https://benefits.ohio.gov",
    OK: "https://okdhslive.org",
    OR: "https://oregonconnects.oregon.gov",
    PA: "https://www.compass.state.pa.us",
    RI: "https://healthyrhode.ri.gov",
    SC: "https://www.scdhhs.gov/snap",
    SD: "https://dss.sd.gov/foodstamps",
    TN: "https://faonline.tn.gov",
    TX: "https://yourtexasbenefits.com",
    UT: "https://jobs.utah.gov/mycase",
    VT: "https://www.mybenefits.vt.gov",
    VA: "https://commonhelp.virginia.gov",
    WA: "https://www.washingtonconnection.org",
    WV: "https://dhhr.wv.gov/bcf/snap",
    WI: "https://access.wisconsin.gov",
    WY: "https://wyo.gov/residents/social-services/snap",
  },

  // ── WIC ─────────────────────────────────────────────────────────────────────
  "wic-nutrition-program": {
    AL: "https://www.alabamapublichealth.gov/wic",
    AK: "https://health.alaska.gov/dph/wcfh/pages/wic",
    AZ: "https://www.azdhs.gov/prevention/nutrition-physical-activity/wic",
    AR: "https://www.healthy.arkansas.gov/programs-services/topics/wic",
    CA: "https://www.cdph.ca.gov/Programs/CFH/DWICSN/Pages/WICSNL.aspx",
    CO: "https://cdphe.colorado.gov/wic",
    CT: "https://portal.ct.gov/DPH/WIC/WIC---Women-Infants--Children",
    DE: "https://dhss.delaware.gov/dhss/dph/chca/wic.html",
    DC: "https://dchealth.dc.gov/service/wic-program",
    FL: "https://www.floridahealth.gov/programs-and-services/wic",
    GA: "https://dph.georgia.gov/wic",
    HI: "https://health.hawaii.gov/wic",
    ID: "https://healthandwelfare.idaho.gov/services/wic",
    IL: "https://www.dph.illinois.gov/topics-services/life-stages-populations/maternal-infant-child/wic",
    IN: "https://www.in.gov/isdh/programs/wic",
    IA: "https://idph.iowa.gov/wic",
    KS: "https://www.kdheks.gov/WIC",
    KY: "https://chfs.ky.gov/agencies/dph/dmc/nab/Pages/wic.aspx",
    LA: "https://ldh.la.gov/page/wic",
    ME: "https://www.maine.gov/dhhs/mecdc/population-health/wic",
    MD: "https://phpa.health.maryland.gov/mch/pages/wic.aspx",
    MA: "https://www.mass.gov/wic-nutrition-program",
    MI: "https://www.michigan.gov/mdhhs/0,5885,7-339-71547_4910_4920---,00.html",
    MN: "https://www.health.state.mn.us/people/wic",
    MS: "https://msdh.ms.gov/msdhsite/_static/41,0,132.html",
    MO: "https://health.mo.gov/living/families/wic",
    MT: "https://dphhs.mt.gov/publichealth/wic",
    NE: "https://dhhs.ne.gov/Pages/WIC.aspx",
    NV: "https://dpbh.nv.gov/Programs/WIC/WIC_-_Home",
    NH: "https://www.dhhs.nh.gov/dphs/nhp/wic",
    NJ: "https://www.nj.gov/health/fhs/wic",
    NM: "https://www.nmhealth.org/about/phd/fch/wic",
    NY: "https://www.health.ny.gov/prevention/nutrition/wic",
    NC: "https://www.nutritionnc.com",
    ND: "https://www.hhs.nd.gov/wic",
    OH: "https://odh.ohio.gov/know-our-programs/wic",
    OK: "https://oklahoma.gov/health/family-health/wic.html",
    OR: "https://www.oregon.gov/oha/ph/HealthyPeopleFamilies/WIC/Pages/index.aspx",
    PA: "https://www.health.pa.gov/topics/programs/WIC/Pages/WIC.aspx",
    RI: "https://health.ri.gov/programs/detail.php?pgm_id=66",
    SC: "https://www.scdhec.gov/health/womens-childrens-health/women-infants-children-wic",
    SD: "https://doh.sd.gov/special-populations/wic",
    TN: "https://www.tn.gov/health/health-program-areas/fhw/wic.html",
    TX: "https://www.texaswic.org",
    UT: "https://health.utah.gov/wic",
    VT: "https://www.healthvermont.gov/family/wic",
    VA: "https://www.vdh.virginia.gov/wic",
    WA: "https://www.doh.wa.gov/YouandYourFamily/WIC",
    WV: "https://dhhr.wv.gov/wic",
    WI: "https://www.dhs.wisconsin.gov/wic",
    WY: "https://health.wyo.gov/publichealth/womens-and-childrens-health-unit/wic",
  },

  // ── TANF ────────────────────────────────────────────────────────────────────
  "tanf-cash-assistance": {
    AL: "https://dhr.alabama.gov/family-assistance",
    AK: "https://dhss.alaska.gov/dpa/Pages/tanf/default.aspx",
    AZ: "https://healthearizonaplus.gov",
    AR: "https://access.arkansas.gov",
    CA: "https://benefitscal.com",
    CO: "https://coloradopeak.secure.force.com",
    CT: "https://www.connect.ct.gov",
    DE: "https://assist.dhss.delaware.gov",
    DC: "https://dhs.dc.gov/service/tanf",
    FL: "https://access.florida.gov",
    GA: "https://dfcs.georgia.gov/tanf",
    HI: "https://pais.dhs.hawaii.gov",
    ID: "https://healthandwelfare.idaho.gov/services/cash-assistance/tanf",
    IL: "https://abe.illinois.gov",
    IN: "https://www.in.gov/fssa/dfr/tanf",
    IA: "https://dhs.iowa.gov/fip",
    KS: "https://www.kansasbenefits.org",
    KY: "https://kynect.ky.gov",
    LA: "https://dcfs.louisiana.gov/tanf",
    ME: "https://www.maine.gov/dhhs/ofi/programs-services/tanf",
    MD: "https://mymdthink.maryland.gov",
    MA: "https://www.mass.gov/cash-assistance",
    MI: "https://mibridges.michigan.gov",
    MN: "https://mnbenefits.mn.gov",
    MS: "https://www.mdhs.ms.gov/economic-assistance/tanf",
    MO: "https://mydss.mo.gov",
    MT: "https://dphhs.mt.gov/tanf",
    NE: "https://dhhs.ne.gov/Pages/ADC.aspx",
    NV: "https://dwss.nv.gov",
    NH: "https://nheasy.nh.gov",
    NJ: "https://www.njhelps.org",
    NM: "https://www.hsd.state.nm.us/tanf",
    NY: "https://mybenefits.ny.gov",
    NC: "https://epass.nc.gov",
    ND: "https://www.hhs.nd.gov/economic-assistance/tanf",
    OH: "https://benefits.ohio.gov",
    OK: "https://okdhslive.org",
    OR: "https://oregonconnects.oregon.gov",
    PA: "https://www.compass.state.pa.us",
    RI: "https://healthyrhode.ri.gov",
    SC: "https://www.dss.sc.gov/tanf",
    SD: "https://dss.sd.gov/tanf",
    TN: "https://www.tn.gov/humanservices/for-families/families-first-tennessee.html",
    TX: "https://yourtexasbenefits.com",
    UT: "https://jobs.utah.gov/mycase",
    VT: "https://www.mybenefits.vt.gov",
    VA: "https://commonhelp.virginia.gov",
    WA: "https://www.washingtonconnection.org",
    WV: "https://dhhr.wv.gov/bcf/tanf",
    WI: "https://access.wisconsin.gov",
    WY: "https://wyo.gov/residents/social-services/tanf",
  },

  // ── LIHEAP ──────────────────────────────────────────────────────────────────
  "liheap-energy-assistance": {
    AL: "https://dhr.alabama.gov/liheap",
    AK: "https://dhss.alaska.gov/dpa/pages/liheap/default.aspx",
    AZ: "https://des.az.gov/services/basic-needs/utilities",
    AR: "https://humanservices.arkansas.gov/divisions-sharedservices/county-operations/liheap",
    CA: "https://www.csd.ca.gov/Pages/EnergyAssistance.aspx",
    CO: "https://cdhs.colorado.gov/low-income-energy-assistance-program",
    CT: "https://www.ct.gov/dss/cwp/view.asp?a=2353&q=305236",
    DE: "https://www.dhss.delaware.gov/dhss/dss/energyassist.html",
    DC: "https://dhs.dc.gov/service/liheap",
    FL: "https://www.floridacommerce.com/divisions/workforce-services/community-services/liheap",
    GA: "https://dfcs.georgia.gov/energy-assistance",
    HI: "https://pais.dhs.hawaii.gov",
    ID: "https://healthandwelfare.idaho.gov/services/energy-assistance/liheap",
    IL: "https://dceo.illinois.gov/communityservices/energyassistance",
    IN: "https://www.in.gov/iocapp/liheap",
    IA: "https://dhs.iowa.gov/energy-assistance",
    KS: "https://www.dcf.ks.gov/services/energyassist",
    KY: "https://chfs.ky.gov/agencies/dcbs/dfs/pnb/Pages/liheap.aspx",
    LA: "https://www.dcfs.louisiana.gov/page/energy-assistance",
    ME: "https://www.maine.gov/dhhs/ofi/programs-services/heap",
    MD: "https://dhs.maryland.gov/office-of-home-energy-programs",
    MA: "https://www.mass.gov/how-to/apply-for-help-paying-your-heating-bills",
    MI: "https://mibridges.michigan.gov",
    MN: "https://mn.gov/deed/job-seekers/programs-and-services/energy",
    MS: "https://www.mdhs.ms.gov/low-income/liheap",
    MO: "https://mydss.mo.gov",
    MT: "https://dphhs.mt.gov/liheap",
    NE: "https://dhhs.ne.gov/Pages/LIHEAP.aspx",
    NV: "https://dwss.nv.gov/programs/liheap",
    NH: "https://www.dhhs.nh.gov/programs-services/economic-assistance/electric-assistance-program",
    NJ: "https://www.nj.gov/dca/dhcr/offices/hvhs.shtml",
    NM: "https://www.hsd.state.nm.us/lus/low-income-energy-assistance-program.aspx",
    NY: "https://mybenefits.ny.gov",
    NC: "https://www.ncdhhs.gov/assistance/low-income-services/low-income-energy-assistance",
    ND: "https://www.hhs.nd.gov/economic-assistance/energy-assistance",
    OH: "https://energyhelp.ohio.gov",
    OK: "https://okdhslive.org",
    OR: "https://oregonconnects.oregon.gov",
    PA: "https://www.compass.state.pa.us",
    RI: "https://healthyrhode.ri.gov",
    SC: "https://www.dss.sc.gov/energy-assistance",
    SD: "https://dss.sd.gov/energyassistance",
    TN: "https://www.tn.gov/humanservices/for-families/liheap.html",
    TX: "https://www.tdhca.state.tx.us/community-affairs/csbg-liheap.htm",
    UT: "https://jobs.utah.gov/mycase",
    VT: "https://dcf.vermont.gov/benefits/fuelassistance",
    VA: "https://www.dss.virginia.gov/benefit/liheap.cgi",
    WA: "https://www.commerce.wa.gov/building-infrastructure/energy/low-income-weatherization-and-energy-assistance",
    WV: "https://dhhr.wv.gov/bcf/services/liheap",
    WI: "https://access.wisconsin.gov",
    WY: "https://wyo.gov/residents/social-services/liheap",
  },

  // ── Child Care Development Fund ─────────────────────────────────────────────
  "child-care-development-fund": {
    AL: "https://dhr.alabama.gov/child-care",
    AK: "https://dhss.alaska.gov/dpa/Pages/childcare/default.aspx",
    AZ: "https://des.az.gov/services/child-and-family/childcare-subsidy",
    AR: "https://humanservices.arkansas.gov/divisions-sharedservices/child-care-early-childhood-education",
    CA: "https://www.cdss.ca.gov/inforesources/child-care-assistance",
    CO: "https://coloradopeak.secure.force.com",
    CT: "https://www.ct.gov/oec/cwp/view.asp?a=4541&q=536710",
    DE: "https://kids.delaware.gov/fs/childcare.shtml",
    DC: "https://osse.dc.gov/service/child-care-subsidy-program",
    FL: "https://myflorida.com/childcare",
    GA: "https://decal.ga.gov/ChildCareServices/SubsidyPrograms.aspx",
    HI: "https://humanservices.hawaii.gov/bessd/childcare",
    ID: "https://healthandwelfare.idaho.gov/services/child-care/child-care-assistance",
    IL: "https://www.dhs.state.il.us/page.aspx?item=30357",
    IN: "https://www.in.gov/fssa/cafo",
    IA: "https://dhs.iowa.gov/child-care-assistance",
    KS: "https://www.dcf.ks.gov/services/childcare",
    KY: "https://chfs.ky.gov/agencies/dcbs/dfs/ccb/Pages/ccap.aspx",
    LA: "https://www.louisianabelieves.com/schools/child-care-assistance-program",
    ME: "https://www.maine.gov/dhhs/ofi/programs-services/child-care",
    MD: "https://earlychildhood.marylandpublicschools.org/child-care-subsidy-program",
    MA: "https://www.eec.state.ma.us/pub/subvoucher.aspx",
    MI: "https://www.michigan.gov/mdhhs/0,5885,7-339-71547_30664_71548---,00.html",
    MN: "https://mn.gov/dhs/people-we-serve/adults-with-disabilities/services/child-protection/programs-services/child-care-assistance.jsp",
    MS: "https://www.mdhs.ms.gov/early-childhood/child-care-payment-program",
    MO: "https://dss.mo.gov/childcare",
    MT: "https://dphhs.mt.gov/childcare",
    NE: "https://dhhs.ne.gov/Pages/Child-Care-Subsidy.aspx",
    NV: "https://dcfs.nv.gov/Programs/ChildCare/ChildCare",
    NH: "https://www.dhhs.nh.gov/programs-services/child-protection-juvenile-justice/child-care-licensing-and-quality/child-care-scholarship",
    NJ: "https://www.nj.gov/dcf/families/before/afford",
    NM: "https://cyfd.org/child-care",
    NY: "https://ocfs.ny.gov/programs/childcare/subsidy",
    NC: "https://ncchildcare.ncdhhs.gov/Home/Portals/Families/Financial-Help",
    ND: "https://www.hhs.nd.gov/childcare",
    OH: "https://jfs.ohio.gov/occ",
    OK: "https://okdhs.org/services/child-care",
    OR: "https://www.oregon.gov/odhs/child-care/pages/financial-assistance.aspx",
    PA: "https://www.compass.state.pa.us",
    RI: "https://www.ccap.ri.gov",
    SC: "https://www.dss.sc.gov/child-care-and-development",
    SD: "https://dss.sd.gov/childcare",
    TN: "https://www.tn.gov/humanservices/for-families/child-care-services.html",
    TX: "https://www.childcaretexas.com",
    UT: "https://jobs.utah.gov/childcare",
    VT: "https://dcf.vermont.gov/cdd/childcare",
    VA: "https://www.dss.virginia.gov/family/cc/index.cgi",
    WA: "https://www.dcyf.wa.gov/services/earlylearning-childcare/childcare-assistance",
    WV: "https://dhhr.wv.gov/bcf/services/childcare",
    WI: "https://access.wisconsin.gov",
    WY: "https://edu.wyoming.gov/for-families/wyoming-childcare",
  },

  // ── Section 8 / Housing Choice Voucher ──────────────────────────────────────
  "hud-section-8-housing-choice-voucher": {
    AL: "https://www.ahfa.com/rental-professionals/housing-choice-voucher",
    AK: "https://www.ahfc.us/assistance/rental-assistance/section-8-housing-choice-voucher",
    AZ: "https://www.azhousing.gov/programs/housing-choice-voucher",
    AR: "https://www.arkansaspha.com",
    CA: "https://www.hcd.ca.gov/policy-research/docs/hcvp.pdf",
    CO: "https://www.codoa.org/resources/housing-assistance",
    CT: "https://portal.ct.gov/DOH/DOH/Programs/Section-8-Housing-Choice-Voucher",
    DE: "https://www.destatehousing.com/ForRenters/rr_section8.php",
    DC: "https://dcha.dc.gov/service/housing-choice-vouchers",
    FL: "https://www.floridahousing.org/programs/rental-programs/section-8-housing-choice-voucher",
    GA: "https://www.dca.ga.gov/safe-affordable-housing/rental-housing-assistance/georgia-rental-assistance",
    HI: "https://hihousing.hawaii.gov/renters/section-8-voucher-program",
    ID: "https://www.ihfa.org/renters/rental-assistance",
    IL: "https://www.ihda.org/renters/find-housing",
    IN: "https://www.in.gov/ihcda/renters/rental-assistance",
    IA: "https://www.iowafinanceauthority.gov/renters",
    KS: "https://www.kshousingcorp.org/renters/section-8",
    KY: "https://www.kyhousing.org/Programs/Renters/Pages/Section8.aspx",
    LA: "https://www.lhfa.state.la.us/renters",
    ME: "https://www.mainehousing.org/programs-services/rental-housing/rental-assistance",
    MD: "https://www.dhcd.maryland.gov/Residents/Pages/RentalAssistance.aspx",
    MA: "https://www.mass.gov/service-details/masshousing-section-8",
    MI: "https://www.michigan.gov/mshda/renters/section-8",
    MN: "https://www.mnhousing.gov/renters",
    MS: "https://www.mshomecorp.com/programs/rental-assistance",
    MO: "https://www.mhdc.com/renters",
    MT: "https://housing.mt.gov/Renters/Rental-Assistance",
    NE: "https://www.nifa.org/renters",
    NV: "https://www.nevadahousing.org/renters",
    NH: "https://www.nhhfa.org/renters/section-8",
    NJ: "https://njdca.gov/renters",
    NM: "https://www.housingnm.org/renters",
    NY: "https://hcr.ny.gov/section-8",
    NC: "https://www.nchfa.com/renters/section-8",
    ND: "https://www.ndhfa.org/renters",
    OH: "https://ohiohome.org/renters",
    OK: "https://www.ohfa.org/renters",
    OR: "https://www.ohcs.oregon.gov/renters",
    PA: "https://www.phfa.org/renters",
    RI: "https://www.rihousing.com/renters",
    SC: "https://www.schousing.com/renters",
    SD: "https://www.sdhda.org/renters",
    TN: "https://thda.org/renters",
    TX: "https://www.tdhca.state.tx.us/section-8",
    UT: "https://www.utahhousingcorp.org/renters",
    VT: "https://www.vhfa.org/renters",
    VA: "https://www.vhda.com/renters",
    WA: "https://www.wshfc.org/renters",
    WV: "https://www.wvhdf.com/renters",
    WI: "https://www.wheda.com/renters",
    WY: "https://wyomingcda.com/renters",
  },

  // ── Weatherization Assistance Program ───────────────────────────────────────
  "doe-weatherization-assistance-program": {
    AL: "https://adeca.alabama.gov/weatherization",
    AK: "https://www.commerce.alaska.gov/web/ahfc/programs/weatherization",
    AZ: "https://des.az.gov/services/basic-needs/utilities/weatherization",
    AR: "https://humanservices.arkansas.gov/weatherization",
    CA: "https://www.csd.ca.gov/Pages/Weatherization.aspx",
    CO: "https://cdhs.colorado.gov/weatherization",
    CT: "https://www.ct.gov/ecd/cwp/view.asp?a=4339&Q=506186",
    DE: "https://www.dnrec.delaware.gov/energy/Pages/Weatherization.aspx",
    DC: "https://doee.dc.gov/weatherization",
    FL: "https://www.floridacommerce.com/divisions/workforce-services/community-services/weatherization",
    GA: "https://www.dca.ga.gov/community-economic-development/community-development-division/programs-and-incentives/weatherization-assistance",
    HI: "https://energy.hawaii.gov/programs/weatherization",
    ID: "https://healthandwelfare.idaho.gov/services/energy-assistance/weatherization",
    IL: "https://dceo.illinois.gov/communityservices/weatherization",
    IN: "https://www.in.gov/ihcda/homeowners/weatherization",
    IA: "https://www.ieda.iowa.gov/weatherization",
    KS: "https://www.dcf.ks.gov/services/csbg/weatherization",
    KY: "https://chfs.ky.gov/agencies/dcbs/dfs/pnb/Pages/wap.aspx",
    LA: "https://www.dcfs.louisiana.gov/weatherization",
    ME: "https://www.efficiencymaine.com/at-home/weatherization-assistance",
    MD: "https://dhcd.maryland.gov/Residents/Pages/Weatherization.aspx",
    MA: "https://www.mass.gov/how-to/apply-for-weatherization-services",
    MI: "https://www.michigan.gov/mdhhs/0,5885,7-339-71547_4910_4920_4930---,00.html",
    MN: "https://mn.gov/commerce/consumers/your-home/energy-assistance/weatherization.jsp",
    MS: "https://www.mdhs.ms.gov/low-income/weatherization",
    MO: "https://dss.mo.gov/weatherization",
    MT: "https://dphhs.mt.gov/weatherization",
    NE: "https://nifa.org/homeowners/weatherization",
    NV: "https://housing.nv.gov/weatherization",
    NH: "https://www.dhhs.nh.gov/programs-services/economic-assistance/weatherization",
    NJ: "https://nj.gov/dca/dhcr/offices/weatherization.shtml",
    NM: "https://www.housingnm.org/weatherization",
    NY: "https://www.nyserda.ny.gov/All-Programs/WAP",
    NC: "https://nccommerce.com/weatherization",
    ND: "https://www.communityservices.nd.gov/weatherization",
    OH: "https://development.ohio.gov/weatherization",
    OK: "https://okcommerce.gov/community-development/weatherization",
    OR: "https://www.oregon.gov/ohcs/energy-weatherization/pages/weatherization-program.aspx",
    PA: "https://www.dced.pa.gov/weatherization",
    RI: "https://www.energy.ri.gov/weatherization",
    SC: "https://www.dss.sc.gov/weatherization",
    SD: "https://dlr.sd.gov/weatherization",
    TN: "https://www.tn.gov/humanservices/for-families/weatherization.html",
    TX: "https://www.tdhca.state.tx.us/community-affairs/weatherization.htm",
    UT: "https://housing.utah.gov/weatherization",
    VT: "https://www.efficiencyvermont.com/services/weatherization",
    VA: "https://www.dhcd.virginia.gov/weatherization",
    WA: "https://www.commerce.wa.gov/building-infrastructure/energy/weatherization",
    WV: "https://www.wvdo.org/weatherization",
    WI: "https://www.dhs.wisconsin.gov/weatherization",
    WY: "https://wyomingcda.com/weatherization",
  },

  // ── Emergency Rental Assistance ──────────────────────────────────────────────
  "emergency-rental-assistance": {
    AL: "https://www.ahfa.com/rental-assistance",
    AK: "https://www.ahfc.us/assistance/rental-assistance/era",
    AZ: "https://www.azhousing.gov/rental-assistance",
    AR: "https://www.ihfa.state.ar.us/rental-assistance",
    CA: "https://housing.ca.gov/covid_rr",
    CO: "https://www.colorado.gov/pacific/cdhs/rental-assistance",
    CT: "https://www.chfa.org/renters",
    DE: "https://destatehousing.com/rental-assistance",
    DC: "https://dhs.dc.gov/service/emergency-rental-assistance",
    FL: "https://www.floridahousing.org/rental-assistance",
    GA: "https://georgia.gov/rental-assistance",
    HI: "https://hihousing.hawaii.gov/era",
    ID: "https://www.ihfa.org/rental-assistance",
    IL: "https://www.ihda.org/rental-assistance",
    IN: "https://www.in.gov/ihcda/rental-assistance",
    IA: "https://www.iowafinanceauthority.gov/rental-assistance",
    KS: "https://www.kshousingcorp.org/rental-assistance",
    KY: "https://www.kyhousing.org/rental-assistance",
    LA: "https://lhfa.state.la.us/rental-assistance",
    ME: "https://www.mainehousing.org/rental-assistance",
    MD: "https://www.dhcd.maryland.gov/rental-assistance",
    MA: "https://www.mass.gov/rental-assistance",
    MI: "https://www.michigan.gov/mshda/rental-assistance",
    MN: "https://www.mnhousing.gov/rental-assistance",
    MS: "https://www.mshomecorp.com/rental-assistance",
    MO: "https://www.mhdc.com/rental-assistance",
    MT: "https://housing.mt.gov/rental-assistance",
    NE: "https://www.nifa.org/rental-assistance",
    NV: "https://www.nevadahousing.org/rental-assistance",
    NH: "https://www.nhhfa.org/rental-assistance",
    NJ: "https://www.njdca.gov/rental-assistance",
    NM: "https://www.housingnm.org/rental-assistance",
    NY: "https://otda.ny.gov/programs/emergency-rental-assistance",
    NC: "https://www.nchfa.com/rental-assistance",
    ND: "https://www.ndhfa.org/rental-assistance",
    OH: "https://ohiohome.org/rental-assistance",
    OK: "https://www.ohfa.org/rental-assistance",
    OR: "https://www.ohcs.oregon.gov/rental-assistance",
    PA: "https://www.phfa.org/rental-assistance",
    RI: "https://www.rihousing.com/rental-assistance",
    SC: "https://www.schousing.com/rental-assistance",
    SD: "https://www.sdhda.org/rental-assistance",
    TN: "https://thda.org/rental-assistance",
    TX: "https://www.tdhca.state.tx.us/rental-assistance",
    UT: "https://www.utahhousingcorp.org/rental-assistance",
    VT: "https://www.vhfa.org/rental-assistance",
    VA: "https://www.vhda.com/rental-assistance",
    WA: "https://www.wshfc.org/rental-assistance",
    WV: "https://www.wvhdf.com/rental-assistance",
    WI: "https://www.wheda.com/rental-assistance",
    WY: "https://wyomingcda.com/rental-assistance",
  },

  // ── HOMES Rebate (IRA) ───────────────────────────────────────────────────────
  "ira-homes-rebate-program": {
    AL: "https://energy.alabama.gov/rebates",
    AK: "https://www.commerce.alaska.gov/web/ahfc/programs/rebates",
    AZ: "https://www.azcommerce.com/energy-rebates",
    AR: "https://www.arkansasenergy.org/rebates",
    CA: "https://www.energy.ca.gov/programs-and-topics/programs/clean-energy-rebates",
    CO: "https://energyoffice.colorado.gov/rebates",
    CT: "https://www.energizect.com/rebates",
    DE: "https://www.energizedelaware.org/rebates",
    DC: "https://doee.dc.gov/rebates",
    FL: "https://floridagreenbuildingcoalition.org/rebates",
    GA: "https://www.georgiapowerrebates.com",
    HI: "https://energy.hawaii.gov/rebates",
    ID: "https://www.idahoenergy.org/rebates",
    IL: "https://illinois.gov/energy-rebates",
    IN: "https://www.in.gov/iurc/consumer-information/energy-rebates",
    IA: "https://www.ieda.iowa.gov/energy-rebates",
    KS: "https://www.kcc.state.ks.us/energy-rebates",
    KY: "https://energy.ky.gov/rebates",
    LA: "https://www.louisianaunlimitedpower.com/rebates",
    ME: "https://www.efficiencymaine.com/rebates",
    MD: "https://energy.maryland.gov/rebates",
    MA: "https://www.masssave.com/rebates",
    MI: "https://www.michigan.gov/mpsc/energy-rebates",
    MN: "https://mn.gov/commerce/consumers/your-home/rebates",
    MS: "https://www.mississippipower.com/rebates",
    MO: "https://energy.mo.gov/rebates",
    MT: "https://deq.mt.gov/energy/rebates",
    NE: "https://www.oppd.com/rebates",
    NV: "https://www.nvenergy.com/rebates",
    NH: "https://www.nhsaves.com/rebates",
    NJ: "https://www.njcleanenergy.com/residential/rebates",
    NM: "https://www.pnmenergy.com/rebates",
    NY: "https://www.nyserda.ny.gov/rebates",
    NC: "https://energync.org/rebates",
    ND: "https://www.nd.gov/nddes/energy-rebates",
    OH: "https://energyforward.ohio.gov/rebates",
    OK: "https://www.ogeelectric.com/rebates",
    OR: "https://www.energytrust.org/rebates",
    PA: "https://www.pennenergy.org/rebates",
    RI: "https://www.ri-energy.com/rebates",
    SC: "https://www.scpowerteam.com/rebates",
    SD: "https://www.ote.sd.gov/rebates",
    TN: "https://www.tva.com/energy-products/rebates",
    TX: "https://www.seco.cpa.texas.gov/rebates",
    UT: "https://energy.utah.gov/rebates",
    VT: "https://www.efficiencyvermont.com/rebates",
    VA: "https://www.dom.com/rebates",
    WA: "https://www.commerce.wa.gov/building-infrastructure/energy/rebates",
    WV: "https://www.wvdo.org/energy-rebates",
    WI: "https://focusonenergy.com/rebates",
    WY: "https://www.wyenergy.org/rebates",
  },

  // ── HEEHRA Rebate (IRA) ──────────────────────────────────────────────────────
  "ira-heehra-rebate-program": {
    AL: "https://energy.alabama.gov/heehra",
    AK: "https://www.commerce.alaska.gov/web/ahfc/programs/heehra",
    AZ: "https://www.azcommerce.com/heehra",
    AR: "https://www.arkansasenergy.org/heehra",
    CA: "https://www.energy.ca.gov/programs-and-topics/programs/heehra",
    CO: "https://energyoffice.colorado.gov/heehra",
    CT: "https://www.energizect.com/heehra",
    DE: "https://www.energizedelaware.org/heehra",
    DC: "https://doee.dc.gov/heehra",
    FL: "https://floridagreenbuildingcoalition.org/heehra",
    GA: "https://www.georgiapowerrebates.com/heehra",
    HI: "https://energy.hawaii.gov/heehra",
    ID: "https://www.idahoenergy.org/heehra",
    IL: "https://illinois.gov/heehra",
    IN: "https://www.in.gov/heehra",
    IA: "https://www.ieda.iowa.gov/heehra",
    KS: "https://www.kcc.state.ks.us/heehra",
    KY: "https://energy.ky.gov/heehra",
    LA: "https://www.louisianaunlimitedpower.com/heehra",
    ME: "https://www.efficiencymaine.com/heehra",
    MD: "https://energy.maryland.gov/heehra",
    MA: "https://www.masssave.com/heehra",
    MI: "https://www.michigan.gov/heehra",
    MN: "https://mn.gov/heehra",
    MS: "https://www.mississippipower.com/heehra",
    MO: "https://energy.mo.gov/heehra",
    MT: "https://deq.mt.gov/heehra",
    NE: "https://www.oppd.com/heehra",
    NV: "https://www.nvenergy.com/heehra",
    NH: "https://www.nhsaves.com/heehra",
    NJ: "https://www.njcleanenergy.com/heehra",
    NM: "https://www.pnmenergy.com/heehra",
    NY: "https://www.nyserda.ny.gov/heehra",
    NC: "https://energync.org/heehra",
    ND: "https://www.nd.gov/heehra",
    OH: "https://energyforward.ohio.gov/heehra",
    OK: "https://www.ogeelectric.com/heehra",
    OR: "https://www.energytrust.org/heehra",
    PA: "https://www.pennenergy.org/heehra",
    RI: "https://www.ri-energy.com/heehra",
    SC: "https://www.scpowerteam.com/heehra",
    SD: "https://www.ote.sd.gov/heehra",
    TN: "https://www.tva.com/heehra",
    TX: "https://www.seco.cpa.texas.gov/heehra",
    UT: "https://energy.utah.gov/heehra",
    VT: "https://www.efficiencyvermont.com/heehra",
    VA: "https://www.dom.com/heehra",
    WA: "https://www.commerce.wa.gov/heehra",
    WV: "https://www.wvdo.org/heehra",
    WI: "https://focusonenergy.com/heehra",
    WY: "https://www.wyenergy.org/heehra",
  },
}

export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
  { code: "DC", name: "Washington D.C." }, { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" }, { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" }, { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" }, { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" }, { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" }, { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" }, { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" }, { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" }, { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" }, { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" }, { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" }, { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" }, { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" }, { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" }, { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" }, { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" }, { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" }, { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" }, { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" }, { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" }, { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
]
